### ISSUE TITLE
URL inconsistency in example 

### ISSUE THREAD

**Issue by bckeene** [influxdata/influxdb-client-go#202] opened 2020-09-28 03:25 UTC
Under https://github.com/influxdata/influxdb-client-go#basic-example, the import statement references `"github.com/influxdata/influxdb-client-go/v2"`. Should this be `https://github.com/influxdata/influxdb-client-go`?

**Comment by vlastahajek** [comment] 2020-09-28 11:10
@bckeene,  thanks for posting the issue. The _github.com/influxdata/influxdb-client-go/v2_ is the right URL. The issue is in the paragraph above, where the _import statement, _github.com/influxdata/influxdb-client-go_, is wrong.

**Comment by vlastahajek** [comment] 2020-10-02 09:05
Fixed in the v2.1.0

**Closed by vlastahajek** 2020-10-02 09:05 UTC
