### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by soolaugust** [influxdata/influxdb-client-go#217] opened 2020-12-14 07:51 UTC
I try to connect influxdb with influxdb-client-go, but got following error:

```console
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xa7d8e5]

goroutine 1 [running]:
github.com/influxdata/influxdb-client-go/v2/api.(*organizationsAPI).getOrganizations(0xc0000060f0, 0xc2c460, 0xc0000180a0, 0xc000048c00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	E:/01_Development/12_go/workspace/pkg/mod/github.com/influxdata/influxdb-client-go/v2@v2.2.0/api/organizations.go:89 +0x365
github.com/influxdata/influxdb-client-go/v2/api.(*organizationsAPI).FindOrganizationByName(0xc0000060f0, 0xc2c460, 0xc0000180a0, 0xc0000193a3, 0x5, 0x0, 0x0, 0x0)
	E:/01_Development/12_go/workspace/pkg/mod/github.com/influxdata/influxdb-client-go/v2@v2.2.0/api/organizations.go:98 +0x175
```

my code is as following:

```go
client := influxdb2.NewClient(server, token)
ctx := context.Background()

orgApi := client.OrganizationsAPI()
var organization *domain.Organization
if o, err := orgApi.FindOrganizationByName(ctx, org); err != nil {
...
```

after checking, I think the following codes maybe wrong, as `response.Body` length is not 0, but the error code is not 200, so the `response.JSON200` will be nil, and `response.JSON200.Orgs` will report nil error.

https://github.com/influxdata/influxdb-client-go/blob/c98ebf8e4bf0184d57c79df3115c0a312e747a44/domain/client.gen.go#L24922-L24926

**Comment by vlastahajek** [comment] 2020-12-14 07:57
@soolaugust, thanks for reporting the issue. This seems to be the same problem as in issue #216. I'm currently working on a fix.
What is your setup?

**Comment by soolaugust** [comment] 2020-12-14 08:07
I start influxdb with docker and startup command is following:

```shell
docker run -d -p 38086:8086 --expose 8090 --expose 8099 --name influxDbService influxdb
```

and token is a random string, I use `github.com/influxdata/influxdb-client-go/v2` to connect.

and the version is as following:

```mod
github.com/influxdata/influxdb-client-go/v2 v2.2.0
```

**Comment by vlastahajek** [comment] 2020-12-14 08:22
Has the server been initialised via UI or using setup (either from command-line or from the client)?

**Comment by vlastahajek** [comment] 2020-12-14 08:26
Ok, from the second look I guess you are using InfuxDB 1, right?  If yes, you can use only [the V1 compatility API](https://github.com/influxdata/influxdb-client-go#influxdb-18-api-compatibility), as this client is intended to be used mainly with InfluxDB 2.

**Comment by soolaugust** [comment] 2020-12-14 08:28
Does this mean the `influxdb:latest` docker image is using InfluxDB, right?

**Comment by vlastahajek** [comment] 2020-12-14 08:37
That's V1. V2 needs to be pulled from quay.io repository and ASFAIK it doesn't have the `latest` tag:
`docker pull quay.io/influxdb/influxdb:v2.0.2`
`docker run -d --name influxdb2  --publish 8086:8086 quay.io/influxdb/influxdb::v2.0.2`

**Comment by soolaugust** [comment] 2020-12-14 08:40
Thanks, I will try this image. but I think this is a misleading as people who are new to influxdb will think `influxdb:latest` is the latest version. What do you think of?

**Comment by vlastahajek** [comment] 2020-12-14 08:58
Well, those versions are a bit different and they are both being released (v1 is in maintenance mode).
So, for now, making the `latest` tag that will point to the right released latest version in the single repository is not possible, IMHO.

**Comment by soolaugust** [comment] 2020-12-14 09:00
I see, thanks

**Comment by vlastahajek** [comment] 2020-12-14 09:04
As this issue happens when calling V2 API on V1 server, this is a duplicate of #216.
If you would have another problem, please, post new issue.

**Closed by vlastahajek** 2020-12-14 09:04 UTC
Labels: duplicate

**Comment by LieLieLiekey** [comment] 2021-01-18 13:17
I encountered the same error，my version is 2.0.2，os is mac . 
 when I call the function `api.(*bucketsAPI).FindBucketsByOrgName`, there have a panic error:
```text
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1af8ca9]

goroutine 1 [running]:
github.com/influxdata/influxdb-client-go/api.(*bucketsAPI).getBuckets(0xc0006ae140, 0x22e1be0, 0xc000122008, 0xc00086e360, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/bytedance/go1.15/pkg/mod/github.com/influxdata/influxdb-client-go@v1.4.0/api/buckets.go:95 +0x229
github.com/influxdata/influxdb-client-go/api.(*bucketsAPI).FindBucketsByOrgName(0xc0006ae140, 0x22e1be0, 0xc000122008, 0x2132064, 0x8, 0x0, 0x0, 0x0, 0xc0005bfb30, 0x10567b4, ...)
```

but when i use version 2.0.3, there haven't the panic error .
