### ISSUE TITLE
Client is leaking TCP connections

### ISSUE THREAD

**Issue by coussej** [influxdata/influxdb-client-go#183] opened 2020-08-14 11:00 UTC
I discovered this issue with the grafana flux datasource, but traced it back to the client. It seems TCP connections are not closed after calling `client.Close()`.

Output of the program below:
```
...
Query returned 181 rows
Open TCP connections:       59
Query returned 181 rows
Open TCP connections:       60
Query returned 181 rows
Open TCP connections:       61
Query returned 181 rows
Open TCP connections:       62
...
```

Please run this go program to see for yourself (when on linux, change .8086 to :8086 for the netstat command).
```go
package main

import (
	"context"
	"fmt"
	"log"
	"os/exec"

	influxdb2 "github.com/influxdata/influxdb-client-go"
)

func main() {
	for {
		client := influxdb2.NewClient("https://demo.factry.io:8086", "flux:xulf")
		queryAPI := client.QueryAPI("factry")

		query := `from(bucket: "simulation_tanksystem")
							|> range(start: -2h, stop:-30m)
							|> filter(fn: (r) => r._measurement == "WP1_fill_level")
							|> aggregateWindow(every: 30s, timeSrc: "_start", fn: mean, createEmpty:false)`

		// get parser flux query result
		result, err := queryAPI.Query(context.Background(), query)
		if err != nil {
			fmt.Println(err)
			return
		}
	        defer result.Close()

		count := 0
		// Use Next() to iterate over query result lines
		for result.Next() {
			// Observe when there is new grouping key producing new table
			count++
		}
		fmt.Printf("Query returned %v rows\n", count)
		if result.Err() != nil {
			fmt.Printf("Query error: %s\n", result.Err().Error())
		}

		// Ensures background processes finishes
		client.Close()

		getOpenConns()
	}
}

func getOpenConns() {
	out, err := exec.Command("sh", "-c", `netstat -atn | grep ".8086" | wc -l`).Output()
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("Open TCP connections: %s", out)
}

```

**Comment by aknuds1** [comment] 2020-08-14 11:08
I would change into the following, since query results should be closed. Don't know if it helps with your issue though.

```
		result, err := queryAPI.Query(context.Background(), query)
		if err != nil {
			fmt.Println(err)
			return
		}
		defer result.Close()
```

**Comment by aknuds1** [comment] 2020-08-14 11:30
@vlastahajek Sorry, what's the bug exactly? Will the client still leak connections even if you both call `result.Close()` and `client.Close()`?

**Comment by vlastahajek** [comment] 2020-08-14 11:35
The bug is that Close() should be called automatically by Next() at the end of the stream.

**Comment by aknuds1** [comment] 2020-08-14 11:38
@vlastahajek Aha, I see. I thought the client was supposed to call `.Close` on query results, and implemented that in Grafana.

**Comment by vlastahajek** [comment] 2020-08-14 11:51
I will fix that, however, I'm on Windows 10 and I'm not able to reproduce that. Go 1.4, InfluxDB 1.8.1, InfluxDB 2 beta 16

**Comment by vlastahajek** [comment] 2020-08-14 12:37
Actually, looking at the code I see  Close() is called automatically.  Could not be this a similar problem as in #177?

**Comment by sranka** [comment] 2020-08-14 13:01
@aknuds1 I am able to reproduce this on Ubuntu, there extra scokets that increase the number are in TIMED-WAIT state:
```sh
$ netstat -atn | grep ":8086" 
tcp        0      0 127.0.0.1:35098         127.0.0.1:8086          TIME_WAIT  
tcp        0      0 127.0.0.1:34814         127.0.0.1:8086          TIME_WAIT  
tcp        0      0 127.0.0.1:35022         127.0.0.1:8086          TIME_WAIT  
tcp        0      0 127.0.0.1:34782         127.0.0.1:8086          TIME_WAIT  
tcp        0      0 172.17.0.1:37026        172.17.0.2:8086         TIME_WAIT
```

This is AFAIK a normal state of that depends on OS (https://knowledgebase.progress.com/articles/Article/Can-the-time-a-socket-spends-in-TIMED-WAIT-state-be-reduced). The sockets remain in TIMED-WAIT state for additional 60 seconds in my case:
```sh
$ cat /proc/sys/net/ipv4/tcp_fin_timeout
60
```
The code should better reuse clients to avoid this issue.

**Comment by vlastahajek** [comment] 2020-08-14 13:08
Thnaks @sranka. 
@coussej, I've just noticed the problem now. You should move creating client and query API outside the loop. This will allow reusing HTTP connections between query calls.

**Comment by aknuds1** [comment] 2020-08-14 13:29
@sranka Ah... thank you so much, I wasn't aware of this difference.

**Comment by coussej** [comment] 2020-08-14 14:55
The problem is that in for example grafana, a new client is created for each query request to the backend. This is what I tried to minic in this piece of code (which I updated to include the `defer results.close()`. This results in 100s of lingering TCP connections in state ESTABLISHED on ubuntu, and on macOs:

<img width="551" alt="image" src="https://user-images.githubusercontent.com/9944663/90262279-66b25500-de4e-11ea-8a41-a0a69c01c66b.png">

If you run the code above (you can do this, url and token are valid), the number of connections keeps increasing indefinately. The are not in TIME_WAIT, but in ESTABLISHED, meaning they won't be released after 60 seconds...

<img width="246" alt="image" src="https://user-images.githubusercontent.com/9944663/90262497-aaa55a00-de4e-11ea-95ce-124da3164423.png">



The correct behaviour would be in avny case that client.Close() releases the TCP connection, or am I missing something?

**Comment by aknuds1** [comment] 2020-08-14 15:06
@coussej I'm trying to solve the Grafana problem using the InfluxDB Go client v2 (released ~1 hr ago), that allows us to pass a cached HTTP transport (which is standard for Grafana data sources).

**Comment by aknuds1** [comment] 2020-08-16 09:15
I don't think this issue is relevant after all, since I solved it in Grafana (most likely at least), by re-using HTTP connections.

**Comment by coussej** [comment] 2020-08-17 11:04
@aknuds1 It's indeed solved in Grafana (thanks for that!).

Apart from that, I think it can't be expected that a user of this clients has to pass and re-use his/her own HTTP transport. The simpelest use-case (create client, do something, close client) should work without any special considerations, so I'd expect a client.Close() call to effectively close the TCP connection.

**Comment by aknuds1** [comment] 2020-08-17 11:21
@coussej Wasn't the problem here that closed TCP connections linger in [TIME_WAIT](https://superuser.com/questions/173535/what-are-close-wait-and-time-wait-states) state? My understanding is you can't control this from your program, it's something the OS does, so what you need to do is to re-use your HTTP connections.

**Comment by sranka** [comment] 2020-08-17 11:33
@aknuds1 yes, it was the root cause. Your code in grafana handles the situation the best way possible. The code in this client seems to close everything properly from the go's POV, I don't think that we can force-close the socket.

**Comment by aknuds1** [comment] 2020-08-17 11:35
Thanks for clarifying!

**Comment by vlastahajek** [comment] 2020-08-17 11:50
@aknuds1, yes. The library does all what's needed for proper handling of connections, as mentioned in the [net/http docs](https://golang.org/pkg/net/http/):
> The client must close the response body when finished with it:

**Comment by coussej** [comment] 2020-08-18 09:03
Then what is happening in the piece of code above? When I run this, it results in hundreds of connections in state ESTABLISHED, not in TIME_WAIT -> see https://github.com/influxdata/influxdb-client-go/issues/183#issuecomment-674114033.

What am I not seeing here? :-)

**Comment by aknuds1** [comment] 2020-08-18 09:18
@coussej Does the same problem occur if you move `client := influxdb2.NewClient("https://demo.factry.io:8086", "flux:xulf")` outside of the loop?

**Comment by coussej** [comment] 2020-08-18 09:20
FYI: adding `c.httpService.HTTPClient().CloseIdleConnections()` in the client.Close() function (h) does result in the connections being released after the client.Close().

**Comment by coussej** [comment] 2020-08-18 09:28
> I would try to solve one problem at a time, the right pattern is to re-use the client so connections can be re-used.

@aknuds1 I know, my problem popped up in the grafana datasource and you fixed that :-) so re-using the client (or the transport for the client) is indeed a solution / workaround. My point is that, if that is the expected way to use it, then there should not even be a client.Close function :-) So if this function exists, it must effectively clean up, and it seems that after client.close() the underlying http clients keeps existing and keeps occupying its connections.

**Comment by aknuds1** [comment] 2020-08-18 09:30
I think `client.Close` makes sense, since the client should be cleaned up when you're not using it any longer. However, HTTP connections should be re-used in the meantime, since otherwise they will be lingering in wait state before the OS closes them.

**Comment by coussej** [comment] 2020-08-18 09:36
That is the point: Each client creates its dedicated http.Client, which internally reuses the connections belonging to that client and seems to keep existing after (influx)client.Close(). Hence the growing number of connections. 

The code is just a miminal example to reproduce the issue we saw in the grafana datasource, I'm not actually doing this in real-life.

Anyway, this is my opinion. If you consider this not to be an issue, that that is fine by me.

**Comment by aknuds1** [comment] 2020-08-18 09:38
You're not responding to the point of connections lingering in wait mode though. We've already established that these can't be closed by Go mode, it's the OS' responsibility?

**Comment by coussej** [comment] 2020-08-18 10:08
> You're not responding to the point of connections lingering in wait mode though. We've already established that these can't be closed by Go code, it's the OS' responsibility?

I've answered this in https://github.com/influxdata/influxdb-client-go/issues/183#issuecomment-674114033 and https://github.com/influxdata/influxdb-client-go/issues/183#issuecomment-675357160 

Connection can indeed linger in TIME_WAIT mode and are indeed closed by the OS, so that is indeed normal. However, as mentioned, that is **not** what I'm seeing here: They remain ESTABLISHED, hence they can't be closed by the OS. 

(Try running the code example, it stands on it;s own :-))

> That is also why you should follow my advice and move the client out of the loop, to see if there's still a problem.

Moving the client outside of the loop effectively only opens one connection, as you only create one client.

**Comment by sranka** [comment] 2020-08-18 10:20
@coussej @aknuds1 thank you for the discussion herein. I would end up with the following results:
1. If an application frequently connects to any other server (such as a database), a connection pool must be used. Every influx client has a new connection pool OOTB, reusing a single client is therefore a solution. This might be documented to make things clear.
2. Not reusing the connections might result in exhausting of system/networking resources, i.e. too many sockets being in TIMED-WAIT state.
3. If an influxdb client internally creates a new HTTP client (a default case), it should close all idle connections. We might also better tune the default client to not create any idle connections at all.
4. The influxdb client must be closed, because of the WriteAPI implementation that has an asynchronous retry mechanism that must be stopped on close.
5. Users of this library are free to customize the connection pool and other HTTP/HTTPS specific parameters by using https://github.com/influxdata/influxdb-client-go/blob/fb49b499f9a53778bf4cc9ce62d15b0db3806473/api/http/options.go#L50.

**Comment by aknuds1** [comment] 2020-08-18 10:21
@coussej My point is that if you keep the client in the loop, you _will_ have the problem of connections lingering in the wait state until the OS closes them. We saw that happening in Grafana, so you will have a problem on your hands regardless. You are saying you have a problem with connections lingering in the established state; I don't know why this happens, but my point is that if this problem went away you would still have the problem of connections lingering in the wait state, so you wouldn't be much better off.

**Comment by coussej** [comment] 2020-08-18 11:04
> The connections would still linger in the wait state, as was the problem in Grafana.

I never said the connections linger in TIME_WAIT. They linger in ESTABLISHED. That was also the case in the original grafana issue. TIME_WAIT connections would not be a problem.

What I think should happen: client.Close() releases all active connections back to the OS. What currently happens is that for some reason the underlying net/http tranport connections remain alive (and the connections ESTABLISHED, so not to be cleared by the OS). 

a call to `c.httpService.HTTPClient().CloseIdleConnections()` in client.Close() seems to solve this.

Running the example code will make things clear. When you run `netstat -atn | grep ".8086"` or `netstat -atn | grep ":8086"` you will see hundreds of connections in the established state. When you apply this fix with the CloseIdleConnections, you will only see 1.

**Comment by sranka** [comment] 2020-08-18 11:11
Thank you @coussej, the ESTABLISHED connections are caused by (3) in https://github.com/influxdata/influxdb-client-go/issues/183#issuecomment-675394837 . It is the reason for keeping this issue open, it can be fixed.

**Comment by coussej** [comment] 2020-08-18 11:45
Thanks @sranka , implementing 3 would indeed probably solve this.

**Closed** 2020-08-19 07:34 UTC
